export const VEHICLES = [
    {
        id: 1,
        name: "舒適四人座",
        model: "Toyota Camry / Altis",
        quantity: 15,
        seats: 5,
        maxPassengers: 4,
        maxLuggage: 2,
        dispatchPrice: 2500,
        holidaySurcharge: 200,
        nightSurcharge: 1000,
        baseDistance: 20,
        basePrice: 2500,
        overDistancePrice: 50,
        holidaySurchargeUnder1k: 400,
        holidaySurchargePer1k: 400,
        modelSurcharge: 0,
        offPeakDiscount: 0,
        safetySeatInfantPrice: 200,
        safetySeatInfantMax: 2,
        safetySeatChildPrice: 200,
        safetySeatChildMax: 2,
        safetySeatBoosterPrice: 100,
        safetySeatBoosterMax: 2,
        signboardPrice: 100,
        extraStopPrice: 300,
        remoteAreaPrice: 500,
        crossDistrictPrice: 1000,
        status: true,
        image: "https://cdn-icons-png.flaticon.com/512/3202/3202926.png" // Mock icon
    },
    {
        id: 3,
        name: "進口四人座",
        model: "Tesla Model 3 / BMW 3",
        quantity: 8,
        seats: 5,
        maxPassengers: 4,
        maxLuggage: 2,
        dispatchPrice: 3500,
        holidaySurcharge: 300,
        nightSurcharge: 1200,
        baseDistance: 20,
        basePrice: 3500,
        overDistancePrice: 70,
        holidaySurchargeUnder1k: 500,
        holidaySurchargePer1k: 500,
        modelSurcharge: 500,
        offPeakDiscount: 50,
        safetySeatInfantPrice: 300,
        safetySeatInfantMax: 2,
        safetySeatChildPrice: 300,
        safetySeatChildMax: 2,
        safetySeatBoosterPrice: 150,
        safetySeatBoosterMax: 2,
        signboardPrice: 100,
        extraStopPrice: 400,
        remoteAreaPrice: 600,
        crossDistrictPrice: 1200,
        status: true,
        image: "https://cdn-icons-png.flaticon.com/512/3202/3202926.png"
    },
    {
        id: 5,
        name: "賓士 VITO",
        model: "Mercedes-Benz Vito",
        quantity: 5,
        seats: 9,
        maxPassengers: 7,
        maxLuggage: 7,
        dispatchPrice: 5000,
        holidaySurcharge: 500,
        nightSurcharge: 1500,
        baseDistance: 20,
        basePrice: 5000,
        overDistancePrice: 100,
        holidaySurchargeUnder1k: 800,
        holidaySurchargePer1k: 800,
        modelSurcharge: 1000,
        offPeakDiscount: 0,
        safetySeatInfantPrice: 500,
        safetySeatInfantMax: 3,
        safetySeatChildPrice: 500,
        safetySeatChildMax: 3,
        safetySeatBoosterPrice: 200,
        safetySeatBoosterMax: 3,
        signboardPrice: 200,
        extraStopPrice: 500,
        remoteAreaPrice: 800,
        crossDistrictPrice: 1500,
        status: true,
        image: "https://cdn-icons-png.flaticon.com/512/3202/3202926.png"
    },
    {
        id: 8,
        name: "ALPHARD",
        model: "Toyota Alphard",
        quantity: 3,
        seats: 7,
        maxPassengers: 6,
        maxLuggage: 6,
        dispatchPrice: 6000,
        holidaySurcharge: 600,
        nightSurcharge: 1800,
        baseDistance: 20,
        basePrice: 6000,
        overDistancePrice: 120,
        holidaySurchargeUnder1k: 1000,
        holidaySurchargePer1k: 1000,
        modelSurcharge: 1500,
        offPeakDiscount: 0,
        safetySeatInfantPrice: 500,
        safetySeatInfantMax: 3,
        safetySeatChildPrice: 500,
        safetySeatChildMax: 3,
        safetySeatBoosterPrice: 200,
        safetySeatBoosterMax: 3,
        signboardPrice: 200,
        extraStopPrice: 600,
        remoteAreaPrice: 1000,
        crossDistrictPrice: 2000,
        status: true,
        image: "https://cdn-icons-png.flaticon.com/512/3202/3202926.png"
    }
];
